createdAt: 2014-03-22T21:20:52.239Z
id: web-application-architecture
legacyName: web_application_architecture
tags:
  - angularjs
  - architecture
  - rails
  - web
title: Web Application Architecture
