createdAt: 2014-08-03T00:30:01.622Z
id: form-validation-with-angularjs-and-rails
legacyName: form_validation_with_angularjs_and_rails
tags:
  - angularjs
  - form
  - rails
  - validation
title: Form validation with AngularJS and Rails
