createdAt: 2015-06-25T09:27:38.977Z
id: a-reasonable-starting-point-for-building-a-web-app
legacyName: a_reasonable_starting_point_for_building_a_web_app
tags:
  - app
  - javascript
  - programming
  - web
  - web app
title: A Reasonable Starting Point for Building a Web App
