createdAt: 2015-03-23T02:51:25.328Z
id: give-npm-scripts-a-chance
legacyName: give_npm_scripts_a_chance
tags:
  - iojs
  - nodejs
  - npm
  - scripts
  - task runner
  - tasks
title: Give npm scripts a chance
